### PR TITLE
Bump wharfie to v0.6.7

### PR DESCRIPTION
**Pull request by HarrisonWAffel**
Mirror PR of https://github.com/rancher/system-agent/pull/198 rebased onto main

### CODE REVIEW

**Review by jakefhyde — APPROVED** [review]

**Comment by HarrisonWAffel** [comment]
Merging with a single review as the PR this is mirroring received two approvals

**Comment by brandond** [comment]
🙏🏻  thanks @HarrisonWAffel !

**Comment by brandond** [comment]
Rancher issue:
* https://github.com/rancher/rancher/issues/47379

**Comment by HarrisonWAffel** [comment]
Np!

**Pull request merged**
