### PR TITLE
Alpine Linux Install & Uninstall

### PR DESCRIPTION
**Pull request by gb-123-git**

### CODE REVIEW

**Comment by Oats87** [comment]
@gb-123-git 

Is there a corresponding GitHub issue in the `rancher/rancher` github repository that we can refer to for Alpine support? If not, would you mind filing a github issue on the rancher/rancher repository outlining your desire for support for Alpine linux?

Is the reason you are adding alpine support to the install script so that you can provision downstream Alpine linux based nodes?

Do you need to have as many commits as you do for this? Otherwise, we will squash if we merge.

**Comment by gb-123-git** [comment]
@Oats87 

>Is there a corresponding GitHub issue in the rancher/rancher github repository that we can refer to for Alpine support? If not, would you mind filing a github issue on the rancher/rancher repository outlining your desire for support for Alpine linux?
Is the reason you are adding alpine support to the install script so that you can provision downstream Alpine linux based nodes?"

Actually, I don't know if there is a corresponding issue in the rancher/rancher repository. I needed Alpine support for downstream nodes so I basically wrote the script since I could not find anything which supports Alpine for Nodes ( I think installing Rancher itself on Alpine was somewhere in the docs, but not for the downstream nodes.) Since I installed and tested it, I wanted to contribute something to rancher and share the same with everyone else.
Btw, this is only the part where the downstream nodes get provisioned. Appropriate changes to GUI might need to be made in rancher/rancher repo (eg. checkbox for Alpine)

>'Do you need to have as many commits as you do for this? Otherwise, we will squash if we merge'

Please do ahead and sqaush the commits, I usually work on GitLab and am new to GitHub, so apologies for so many commits, didn't find an option where I could merge/squash them through GitHub Web Gui.

**Comment by gb-123-git** [comment]
@Oats87
Updated my previous comment with issue reference.

**Comment by gb-123-git** [comment]
@Oats87
 Checked on Alpine 3.17 (latest-stable) also. Script seems to be working.

**Comment by gb-123-git** [comment]
@Oats87 
Fixed the script. Just used it to join a Node of alpine Linux on my setup. Can you please check once again ?

**Comment by gb-123-git** [comment]
Any progress on merging this ?

**Comment by gb-123-git** [comment]
@jakefhyde 
Any progress on merging this ? I would prefer to get this merged before any more changes are made to the files at it would be very difficult for me to continuously maintain this. Merging would also help me track the changes so that I can further create merge request for alpine in case any required in future. I can confirm that the script works in Alpine Linux (already installed it to my server) 
Please do look into this. 
Thanks!

**Comment by Oats87** [comment]
@gb-123-git Are you using the `rancher/system-agent` in an application that does not consume the `rancher/system-agent-installer-k3s` or `rancher/system-agent-installer-rke2`? We are hesitant to merge this to add support for Alpine as we do not officially support Alpine with either of our installers at this point.

**Comment by gb-123-git** [comment]
@Oats87 
I am using this script while creating new k3s cluster from rancher and/or register new nodes to an existing cluster. As much as I understand that you do not support Alpine, if you look carefully, I have not even touched the original code written by you guys. All I have done is create an `if` fork for installation in Alpine linux since Alpine uses OpenRC which was not handled earlier.
I really do not understand the hesitation as the code is completely safe and untouched for ALL previous operating systems apart from Alpine (i.e. the code forks into `if` ONLY when it finds that the OS is Alpine)
Further I have been using the code and can confirm there are no errors.

Please let me know in case you need any other clarification and/or have any other hesitation. You can even check that this code would work as before in all your earlier tested OSes.

**Comment by gb-123-git** [comment]
@Oats87 
Waiting for a reply from you. Thanks.

**Pull request closed without merging**
