### PR TITLE
Change base images to `bci-micro`

### PR DESCRIPTION
**Pull request by pjbgf**
Issues:
* https://github.com/rancher/rancher/issues/46098
* https://github.com/rancher/rancher/issues/46621
* https://github.com/rancher/rancher/issues/46623

~Note that `kubectl` is also being bumped to `v1.28.10` as the previously used `v1.27` is EOL.~ - already bumped in another PR

### CODE REVIEW

**Comment by snasovich** [comment]
@pjbgf , thank you for submitting it and apologies for missing reviewing this one - linked issue flew under the radar due to missing labels.
Please resolve new merge conflicts when you have a chance. Please also note we have bumped kubectl separately.

**Comment by pjbgf** [comment]
@snasovich no worries at all, the PR is now rebase. PTAL

**Review by macedogm — COMMENTED** [review]
Approved from the security pov. Will let the final approval for the Hostbusters team (to avoid the PR from being merged by accident).

**Review by jakefhyde — APPROVED** [review]

**Review by snasovich — APPROVED** [review]
LGTM, see the same FIPS packages as in https://github.com/rancher/rancher/pull/46571 were added to prevent potential issues with FIPS-enabled nodes.

**Pull request merged**
